[tool.poetry]
name = "wagtail-tenants"
version = "0.1.0"
description = "Adds multitenancy to wagtail cms"
authors = ["Boris Brue <boris@zuckersalzundpfeffer.de>"]

[tool.poetry.dependencies]
python = "^3.6.2"
black = "^21.11b1"
django-tenants = "^3.3.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
