[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "wagtail-tenants"
authors = [{name = "Boris Brünen", email = "boris@zuckersalzundpfeffer.de"}]
dynamic = ["version", "description"]
